# Generated by Django 4.2.1 on 2023-06-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0004_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
