# Generated by Django 4.2.1 on 2023-06-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0006_contact_testimonial_remove_category_add_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
