# Generated by Django 4.2.1 on 2023-06-16 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0007_contact_add_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Add_date',
            new_name='Publish_date',
        ),
    ]
