# Generated by Django 4.2.1 on 2023-06-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0008_rename_add_date_contact_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='Publish_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
