# Generated by Django 4.2.1 on 2023-06-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0009_testimonial_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='Role',
            field=models.CharField(
                choices=[('1', 'Full Stack Developer'), ('2', 'Backend Developer'), ('3', 'Frontend Developer'),
                         ('4', 'Manager'), ('5', 'Tester'), ('6', 'Intern')], max_length=20),
        ),
    ]
