# Generated by Django 4.2.1 on 2023-06-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0010_alter_testimonial_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='Role',
            field=models.CharField(
                choices=[('Full Stack Developer', 'Full Stack Developer'), ('Backend Developer', 'Backend Developer'),
                         ('Frontend Developer', 'Frontend Developer'), ('Manager', 'Manager'), ('Tester', 'Tester'),
                         ('Intern', 'Intern')], max_length=20),
        ),
    ]
